'use strict';

const mongoose = require('mongoose')

const Fundamentus = new mongoose.Schema({
    created_at: { type: String, required: true, default: (new Date()).toISOString().substr(0, 10) },
    c_Papel: { type: String, required: true },
    c_Cotacao: { type: Number },
    c_Tipo: { type: String },
    c_Dataultcot: { type: String, required: true },
    c_Empresa: { type: String },
    c_Min52sem: { type: Number },
    c_Setor: { type: String },
    c_Max52sem: { type: Number },
    c_Subsetor: { type: String },
    c_Volmed2m: { type: Number },
    c_Valordemercado: { type: Number },
    c_Ultbalancoprocessado: { type: String },
    c_Valordafirma: { type: Number },
    c_NroAcoes: { type: Number },
    c_Dia: { type: Number },
    c_PL: { type: Number },
    c_LPA: { type: Number },
    c_Mes: { type: Number },
    c_PVP: { type: Number },
    c_VPA: { type: Number },
    c_30dias: { type: Number },
    c_PEBIT: { type: Number },
    c_MargBruta: { type: Number },
    c_12meses: { type: Number },
    c_PSR: { type: Number },
    c_MargEBIT: { type: Number },
    c_2020: { type: Number },
    c_PAtivos: { type: Number },
    c_MargLiquida: { type: Number },
    c_2019: { type: Number },
    c_PCapGiro: { type: Number },
    c_EBITAtivo: { type: Number },
    c_2018: { type: Number },
    c_PAtivCircLiq: { type: Number },
    c_ROIC: { type: Number },
    c_2017: { type: Number },
    c_DivYield: { type: Number },
    c_ROE: { type: Number },
    c_2016: { type: Number },
    c_EVEBITDA: { type: Number },
    c_LiquidezCorr: { type: Number },
    c_2015: { type: Number },
    c_EVEBIT: { type: Number },
    c_DivBrPatrim: { type: Number },
    c_CresRec5a: { type: Number },
    c_GiroAtivos: { type: Number },
    c_Ativo: { type: Number },
    c_DivBruta: { type: Number },
    c_Disponibilidades: { type: Number },
    c_DivLiquida: { type: Number },
    c_AtivoCirculante: { type: Number },
    c_PatrimLiq: { type: Number },
    c_ReceitaLiquida: { type: Number },
    c_ReceitaLiquida: { type: Number },
    c_EBIT: { type: Number },
    c_EBIT: { type: Number },
    c_LucroLiquido: { type: Number },
    c_LucroLiquido: { type: Number }
});

module.exports = mongoose.model('fundamentus', Fundamentus);